services:

  app:
    build: .
    ports:
      - "8080:80"

  mysql:
    image: mysql:8
    environment:
      MYSQL_ROOT_PASSWORD: "123456"
      MYSQL_DATABASE: meubanco
      MYSQL_USER: aluno
      MYSQL_PASSWORD: "123456"

  phpmyadmin:
    image: phpmyadmin:latest
    ports:
      - "8081:80"
    environment:
      PMA_HOST: mysql
    depends_on:
      - mysql
